[workspace]

members = [
  "namespaced-id",
  "namespaced-id-core",
  "namespaced-id-macros",
]
resolver = "2"

[workspace.lints.clippy]
enum_glob_use = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
# i just disagree with it
option_if_let_else = "allow"
