[package]
name = "namespaced-id-macros"
version = "0.1.0"
edition = "2024"
description = "Macros for the namespaced-id crate"
license = "GPL-3.0-or-later"
repository = "https://github.com/sautibara/namespaced-id"
readme = "README.md"

[dependencies]
namespaced-id-core = { version = "0.1.0", path = "../namespaced-id-core" }
quote = "1.0.45"
syn = "2.0.117"

[lib]
proc-macro = true

[lints]
workspace = true
