[package]
name = "namespaced-id"
version = "0.1.0"
edition = "2024"
description = "Human-readable identifiers"
license = "GPL-3.0-or-later"
repository = "https://github.com/sautibara/namespaced-id"
readme = "README.md"

[dependencies]
namespaced-id-core = { version = "0.1.0", path = "../namespaced-id-core" }
namespaced-id-macros = { version = "0.1.0", path = "../namespaced-id-macros" }
serde = { version = "1.0.228", optional = true }

[lints]
workspace = true

[features]
serde = ["dep:serde"]
